version: '3'
services:
  web:
    build: .
    ports:
      - '3000:3000'

  db:
    image: mongo
    ports:
      - 27017:27017
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_pass
      MONGO_INITDB_DATABASE: javl
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - db-data:/var/lib/mongo

volumes:
  db-data:
